version: '3.1'
services:
  db:
    image: mysql:8.0.32
    container_name: test-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'