version: '3.1'
services:
  db:
    image: mysql:8.0.32
    container_name: araqichDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: araqichDBNew
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: araqichDB
  web:
    depends_on:
      - db
    build: ./
    container_name: myTomcat
    ports:
      - '8082:8080'
    environment:
      MYSQL_DATABASE: araqichDBNew
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: admin